version: '3'

services:
  db-rassvet:
    image: postgres
    container_name: db-rassvet
    environment:
      - POSTGRES_DB=rassvet
      - POSTGRES_USER=rassvet
      - POSTGRES_PASSWORD=rassvet
    ports:
      - "5432:5432"
    volumes:
     - ./src/resources/db:/docker-entrypoint-initdb.d